### ISSUE TITLE
sc-mongodb 2.0.0 not showing on supermarket

### ISSUE THREAD

**Issue by kpmueller** [sous-chefs/mongodb#214]
On https://supermarket.chef.io/cookbooks/sc-mongodb, the latest available version is 2.0.0. Is this intended?

**Comment by josephholsten** [comment]
@kpmueller want to help us maintain this cookbook? I'd be happy to help get you up to speed, but at the moment we don't have a dedicated maintainer.

**Comment by josephholsten** [comment]
ok, I need to just take care of this. I'm going to get @damacus to help me.

**Comment by kpmueller** [comment]
@josephholsten sorry just saw this. Unfortunately, I don't have time to help at the moment, due to work, but I'll let you know if I do in the future! I know maintainers have a thankless job  :(  We also have less mongodb stuff under chef now that we've moved to Atlas. I was happy sous-chefs took over the mongodb cookbook stuff.

**Comment by hrak** [comment]
The only thing that needs to be done is a `knife supermarket share sc-mongodb` by someone with appropriate privileges (supermarket shows @damacus & @scopenco)

**Comment by mbaitelman** [comment]
This has been addressed. https://supermarket.chef.io/cookbooks/sc-mongodb
Closing.

**Comment by mehagar** [comment]
I'm still not seeing the 2.0.0 version here: https://supermarket.chef.io/cookbooks/sc-mongodb

**Comment by Xorima** [comment]
Hi,

There has never been an official 2.0.0 release, if you check the releases and tags here on github there is no 2.0.0 tag/release. Likewise it was never pushed to supermarket. I would strongly recommend you upgrade to the latest version of this cookbook as the 2.0.0 will not be pushed to supermarket as the codebase has moved on since then.

Thanks

Sous-Chefs
